---
title: "spline_script"
author: "yacine"
date: "2024-10-11"
output: html_document
---

We load and/or install the packages we will be using:

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Refresh environment 


rm(list= ls())
#install.packages("splines2")
#install.packages("rms")
#install.packages('Greg')
library(dplyr)
library(survival)
library(readr)
library(ggplot2)
library(splines)
library(splines2)
library(rms)
library(Greg)

splines::bs
splines2::bSpline

#theme_gtsummary_journal("jama")
```

## We load the data:
```{r}
#dt <- readRDS("/home/yacine/UKBB_beluga/prepped_dt.rds") # full df with exclusions + recoding and all data prepared for survival analysis
dt <- readRDS("/home/yacine/AcclerometerProcessing/prepped_dt.rds")
dt2 <- readRDS("/home/yacine/AcclerometerProcessing/prepped_dt2.rds")
```


## Spline Cox PH fit Using the rms Package:
```{r}

# Renaming the variables for MVPA and Follow-up time (crucial for coxph function to work)
dt <- dt %>% rename(fu_time = `Follow_up time`,
                    MI = `Myocardial Infarction`,
                    mvpa1 = `MVPA min/week`,
                    mvpa2 = `MVPA min/week Machine Learning`,
                    mvpa3 = `MVPA min/week Activity Count`
                    )

dt2 <- dt2 %>% rename(fu_time = `Follow_up time`,
                      MI = `Myocardial Infarction`,
                      mvpa4 = `MVPA min/week Self-Report (IPAQ)`
                      )


# *** Note: We determined the optimal number of knots (nk) for each PA measure using AIC testing.The function only allows nk >= 3. Therefore, the number of knots used corresponds to the lowest AIC value for each.
# As a result, we determined the optimal nk was 4 for PA1 and PA2, and 3 for PA3 and PA4.

# PA1
fit_pa1_stroke <- coxph(Surv(fu_time, Stroke) ~ rcs(mvpa1, 4), data = dt)
fit_pa1_MI <- coxph(Surv(fu_time, MI) ~ rcs(mvpa1, 4), data = dt)

# PA2
fit_pa2_stroke <- coxph(Surv(fu_time, Stroke) ~ rcs(mvpa2, 3), data = dt)
fit_pa2_MI <- coxph(Surv(fu_time, MI) ~ rcs(mvpa2, 3), data = dt)

# PA3
fit_pa3_stroke <- coxph(Surv(fu_time, Stroke) ~ rcs(mvpa3, 3), data = dt)
fit_pa3_MI <- coxph(Surv(fu_time, MI) ~ rcs(mvpa3, 3), data = dt)

# PA4
fit_pa4_stroke <- coxph(Surv(fu_time, Stroke) ~ rcs(mvpa4, 3), data = dt2)
fit_pa4_MI <- coxph(Surv(fu_time, MI) ~ rcs(mvpa4, 3), data = dt2)


```


## Plotting Spline Cox PH Model Using the plotHR Function:
```{r}


# PA1
## Stroke
plotHR(fit_pa1_stroke,
       term = 1,
       xlab = "PA Duration (minutes/week)",
       main = "Cox PH Model for Hazard of Stroke \nby Physical Activity Vector Magnitude (ENMO)",
       xlim = c(0, 1500),
       ylim = c(0.2,4),
       plot.bty = "U"
)

## MI
plotHR(fit_pa1_MI,
       term = 1,
       xlab = "PA Duration (minutes/week)",
       main = "Cox PH Model for Hazard of Mycordial Infarction Risk \nby Physical Activity Vector Magnitude (ENMO)",
       xlim = c(0, 1500),
       ylim = c(0.2,4),
       plot.bty = "U" 
)


# PA2
## Stroke
plotHR(fit_pa2_stroke,
       term = 1,
       xlab = "PA Duration (minutes/week)",
       main = "Cox PH Model for Hazard of Stroke \nby Physical Activity - Machine Learning",
       xlim = c(0, 1500),
       ylim = c(0.2,4),
       plot.bty = "U" 
)

## MI
plotHR(fit_pa2_MI,
       term = 1,
       xlab = "PA Duration (minutes/week)",
       main = "Cox PH Model for Hazard of Mycordial Infarction Risk \nby Physical Activity - Machine Learning",
       xlim = c(0, 1500),
       ylim = c(0.2,4),
       plot.bty = "U" 
)



# PA3
## Stroke
plotHR(fit_pa3_stroke,
       term = 1,
       xlab = "PA Duration (minutes/week)",
       main = "Cox PH Model for Hazard of Stroke \nby Physical Activity - Activity Count",
       xlim = c(0, 4000),
       ylim = c(0.2,4),
       plot.bty = "U" 
)

## MI
plotHR(fit_pa3_MI,
       term = 1,
       xlab = "PA Duration (minutes/week)",
       main = "Cox PH Model for Hazard of Mycordial Infarction Risk \nby Physical Activity - Activity Count",
       xlim = c(0, 4000),
       ylim = c(0.2,4),
       plot.bty = "U" 
)




# PA4
## Stroke
plotHR(fit_pa4_stroke,
       term = 1,
       xlab = "PA Duration (minutes/week)",
       main = "Cox PH Model for Hazard of Stroke \nby Physical Activity - Self-Report (IPAQ)",
       xlim = c(0, 1500),
       ylim = c(0.2,4),
       plot.bty = "U" 
)

## MI
plotHR(fit_pa4_MI,
       term = 1,
       xlab = "PA Duration (minutes/week)",
       main = "Cox PH Model for Hazard of Mycordial Infarction Risk \nby Physical Activity - Self-Report (IPAQ)",
       xlim = c(0, 1500),
       ylim = c(0.2,4),
       plot.bty = "U" 
)


```


## Female vs Male Spline Analysis

```{r}
# PA1
fit_pa1_stroke <- coxph(Surv(fu_time, Stroke) ~ rcs(mvpa1, 4) * Sex, data = dt)
fit_pa1_MI <- coxph(Surv(fu_time, MI) ~ rcs(mvpa1, 4) * Sex, data = dt)

# PA2
fit_pa2_stroke <- coxph(Surv(fu_time, Stroke) ~ rcs(mvpa2, 3) * Sex, data = dt)
fit_pa2_MI <- coxph(Surv(fu_time, MI) ~ rcs(mvpa2, 3) * Sex, data = dt)

# PA3
fit_pa3_stroke <- coxph(Surv(fu_time, Stroke) ~ rcs(mvpa3, 3) * Sex, data = dt)
fit_pa3_MI <- coxph(Surv(fu_time, MI) ~ rcs(mvpa3, 3) * Sex, data = dt)

# PA4
fit_pa4_stroke <- coxph(Surv(fu_time, Stroke) ~ rcs(mvpa4, 3) * Sex, data = dt2)
fit_pa4_MI <- coxph(Surv(fu_time, MI) ~ rcs(mvpa4, 3) * Sex, data = dt2)


```



## Plotting Spline Cox PH Model Using the plotHR Function:
```{r}

# PA1
ggplot(dt, aes(x = mvpa1, y = predict(fit_pa1_stroke, type = "risk"), color = Sex)) +
  geom_line() +
  labs(title = "Hazard of Stroke \nfor Physical Activity Vector Magnitude (ENMO) by Sex",
       x = "PA Duration (minutes/week)",
       y = "Hazard Ratio",
       xlim = c(0, 1500),
       ylim = c(0.2,4),
       color = "Sex")

ggplot(dt, aes(x = mvpa1, y = predict(fit_pa1_MI, type = "risk"), color = Sex)) +
  geom_line() +
  labs(title = "Hazard of MI  \nfor Physical Activity Vector Magnitude (ENMO) by Sex",
       x = "PA Duration (minutes/week)",
       y = "Hazard Ratio",
              xlim = c(0, 1500),
       ylim = c(0.2,4),
       color = "Sex")


# PA2
ggplot(dt, aes(x = mvpa2, y = predict(fit_pa2_stroke, type = "risk"), color = Sex)) +
  geom_line() +
  labs(title = "Hazard of Stroke \nfor Physical Activity Machine Learning by Sex",
       x = "PA Duration (minutes/week)",
       y = "Hazard Ratio",
       xlim = c(0, 1500),
       ylim = c(0.2,4),
       color = "Sex")

ggplot(dt, aes(x = mvpa2, y = predict(fit_pa2_MI, type = "risk"), color = Sex)) +
  geom_line() +
  labs(title = "Hazard of MI  \nfor Physical Activity Machine Learning by Sex",
       x = "PA Duration (minutes/week)",
       y = "Hazard Ratio",
              xlim = c(0, 1500),
       ylim = c(0.2,4),
       color = "Sex")


# PA3
ggplot(dt, aes(x = mvpa3, y = predict(fit_pa3_stroke, type = "risk"), color = Sex)) +
  geom_line() +
  labs(title = "Hazard of Stroke \nfor Physical Activity - Activity Count by Sex",
       x = "PA Duration (minutes/week)",
       y = "Hazard Ratio",
       xlim = c(0, 4000),
       ylim = c(0.2,4),
       color = "Sex")

ggplot(dt, aes(x = mvpa3, y = predict(fit_pa3_MI, type = "risk"), color = Sex)) +
  geom_line() +
  labs(title = "Hazard of MI  \nfor Physical Activity - Activity Count by Sex",
       x = "PA Duration (minutes/week)",
       y = "Hazard Ratio",
       xlim = c(0, 4000),
       ylim = c(0.2,4),
       color = "Sex")



# PA4
ggplot(dt2, aes(x = mvpa4, y = predict(fit_pa4_stroke, type = "risk"), color = Sex)) +
  geom_line() +
  labs(title = "Hazard of Stroke \nfor Physical Activity - Self-Report by Sex",
       x = "PA Duration (minutes/week)",
       y = "Hazard Ratio",
              xlim = c(0, 1500),
       ylim = c(0.2,4),
       color = "Sex")

ggplot(dt2, aes(x = mvpa4, y = predict(fit_pa4_MI, type = "risk"), color = Sex)) +
  geom_line() +
  labs(title = "Hazard of MI  \nfor Physical Activity - Self-Report by Sex",
       x = "PA Duration (minutes/week)",
       y = "Hazard Ratio",
              xlim = c(0, 1500),
       ylim = c(0.2,4),
       color = "Sex")


```




